Namespace(M=1, burn_in=10000, data_dir='./data', dataset='MNIST', extractor='raw_feature', find_k=0, finetune_step=50, gaussian_dim=10, gpu=6, lam=1e-06, len_list=10000, num_removes=1000, num_steps=10000, result_dir='./result', run_baseline=1, search_burnin=0, search_burnin_newdata=0, search_finetune=0, sequential=0, sequential2=1, sigma=0.1, train_mode='binary')
Extracted features not found, loading raw features.
number training data:11982
baseline.py:48: RuntimeWarning: invalid value encountered in matmul
  self.L = np.max(np.linalg.eigvalsh(X.T @ X / self.n)) / 4 + self.args.lam * self.n
L smooth constant0.19470056009960174
m strongly convex:0.011982
M lipschitz constant:1
step size eta:5.136092055864843
RDP constant delta:8.345852111500584e-05
> /scratch3/wang5272/unlearning/baseline.py(581)main()
-> if args.sequential == 1:
(Pdb) 
Traceback (most recent call last):
  File "baseline.py", line 603, in <module>
    main()
  File "baseline.py", line 581, in main
    if args.sequential == 1:
  File "baseline.py", line 581, in main
    if args.sequential == 1:
  File "/homes/wang5272/scratch/anaconda3/envs/eda/lib/python3.8/bdb.py", line 88, in trace_dispatch
    return self.dispatch_line(frame)
  File "/homes/wang5272/scratch/anaconda3/envs/eda/lib/python3.8/bdb.py", line 113, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit
